const products = [
    {
        id: 1,
        name: "Astronaut T-shirt 1",
        image: "/img/product_2.jpg",
        price: 499000,
        discount: 399000,
        rate: 5,
        category: "featured",
    },
    {
        id: 2,
        name: "Astronaut T-shirt 2",
        image: "/img/product_2.jpg",
        price: 249000,
        discount: 199000,
        rate: 4.5,
        category: "featured",
    },
    {
        id: 3,
        name: "Astronaut T-shirt 3",
        image: "/img/product_2.jpg",
        price: 399000,
        discount: 299000,
        rate: 4,
        category: "featured",
    },
    {
        id: 4,
        name: "Astronaut T-shirt 4",
        image: "/img/product_2.jpg",
        price: 499000,
        discount: 399000,
        rate: 5,
        category: "featured",
    },
    {
        id: 5,
        name: "Astronaut T-shirt 5",
        image: "/img/product_2.jpg",
        price: 599000,
        discount: 449000,
        rate: 5,
        category: "new",
    },
    {
        id: 6,
        name: "Astronaut T-shirt 6",
        image: "/img/product_2.jpg",
        price: 649000,
        discount: 599000,
        rate: 4.5,
        category: "new",
    },
    {
        id: 7,
        name: "Astronaut T-shirt 7",
        image: "/img/product_2.jpg",
        price: 300000,
        discount: 299000,
        rate: 4,
        category: "new",
    },
    {
        id: 8,
        name: "Astronaut T-shirt 8",
        image: "/img/product_2.jpg",
        price: 320000,
        discount: 249000,
        rate: 5,
        category: "new",
    },
    {
        id: 9,
        name: "Astronaut T-shirt 9",
        image: "/img/product_2.jpg",
        price: 499000,
        discount: 399000,
        rate: 5,
        category: "old",
    },
    {
        id: 10,
        name: "Astronaut T-shirt 10",
        image: "/img/product_2.jpg",
        price: 249000,
        discount: 199000,
        rate: 4.5,
        category: "old",
    },
    {
        id: 11,
        name: "Astronaut T-shirt 11",
        image: "/img/product_2.jpg",
        price: 399000,
        discount: 299000,
        rate: 4,
        category: "old",
    },
    {
        id: 12,
        name: "Astronaut T-shirt 12",
        image: "/img/product_2.jpg",
        price: 499000,
        discount: 399000,
        rate: 5,
        category: "old",
    },
    {
        id: 13,
        name: "Astronaut T-shirt 13",
        image: "/img/product_2.jpg",
        price: 599000,
        discount: 449000,
        rate: 5,
        category: "old",
    },
    {
        id: 14,
        name: "Astronaut T-shirt 14",
        image: "/img/product_2.jpg",
        price: 649000,
        discount: 599000,
        rate: 4.5,
        category: "old",
    },
    {
        id: 15,
        name: "Astronaut T-shirt 15",
        image: "/img/product_2.jpg",
        price: 300000,
        discount: 299000,
        rate: 4,
        category: "old",
    },
    {
        id: 16,
        name: "Astronaut T-shirt 16",
        image: "/img/product_2.jpg",
        price: 320000,
        discount: 249000,
        rate: 5,
        category: "old",
    },
    {
        id: 17,
        name: "Astronaut T-shirt 17",
        image: "/img/product_2.jpg",
        price: 599000,
        discount: 449000,
        rate: 5,
        category: "old",
    },
    {
        id: 18,
        name: "Astronaut T-shirt 18",
        image: "/img/product_2.jpg",
        price: 649000,
        discount: 599000,
        rate: 4.5,
        category: "old",
    },
    {
        id: 19,
        name: "Astronaut T-shirt 19",
        image: "/img/product_2.jpg",
        price: 300000,
        discount: 299000,
        rate: 4,
        category: "old",
    },
    {
        id: 20,
        name: "Astronaut T-shirt 20",
        image: "/img/product_2.jpg",
        price: 320000,
        discount: 249000,
        rate: 5,
        category: "old",
    }
]

export default products
